### PR TITLE
Updated amplifier HAL

### PR DESCRIPTION
**Pull request by sashascurtu**

### CODE REVIEW

**Comment by idoybh** [comment]
Why pushing the commit with its revert?

**Comment by sashascurtu** [comment]
> Why pushing the commit with its revert?

the patchset was rebased and something new was added with the same commit message

**Comment by idoybh** [comment]
> > Why pushing the commit with its revert?
> 
> the patchset was rebased and something new was added with the same commit message

Still doesn't explain. reset to `b7b923f7981fdeefa3416406a47462603d86febf`

**Comment by gotenksIN** [comment]
if you are reverting and repicking anyways might as well pick the newer squash https://github.com/LineageOS/android_hardware_libhardware/commit/1535276056aa47e1cdca3f4ab8343707c2a36ab5

**Comment by idoybh** [comment]
lol now authorship is wrong?

**Comment by idoybh** [comment]
and commit msg?

**Comment by sashascurtu** [comment]
> lol now authorship is wrong?

what, i just hardreset to my revert and picked the latest squash from los

**Comment by gotenksIN** [comment]
@idoybh eh that looks fine 
It's just a squash from los

**Comment by idoybh** [comment]
thanks again :)

**Pull request merged**
